import Head from "next/head";
import Layout from "@/components/Layout/Layout";
import ContactMe from "@/components/Contact/ContactMe";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Vipin Yadav</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <ContactMe/>
      </Layout>
    </>
  );
}
