import Head from "next/head";
import Layout from "@/components/Layout/Layout";
import Exp from "@/components/Home/Exp/Exp";
import Featured from "@/components/Home/Featured/Featured";
export default function Work() {
  return (
    <>
      <Head>
        <title>Vipin Yadav</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Exp/>
        <Featured/>
      </Layout>
    </>
  );
}
